### PR TITLE
Add pull-request-id option to action.yml for flexible PR commenting

### PR DESCRIPTION
**Pull request by hirosi1900day**
# why
Added a new `pull-request-id` option to `action.yml` to enable commenting on test results for any specified PR. This enhancement addresses the limitation of `github.context.issue.number` which is not available during push events, allowing comments to be posted to a PR even during push events by specifying the PR number.

### CODE REVIEW

**Comment by aki77** [comment]
Thanks for the PR.
I would like to know the specific use cases where `on: pull_request:` is not a good idea.

**Comment by hirosi1900day** [comment]
@aki77 
Thank you for comment!

Some of our engineers prefer to push their changes and ensure the CI passes before creating a pull request. To accommodate this, we want to trigger RSpec on push events and, if a pull request exists, comment the RSpec results on the pull request. This is the reason for the changes made in this PR.

**Comment by aki77** [comment]
What are the problems with the following settings?

```
on:
  pull_request:
  push:
```

**Comment by hirosi1900day** [comment]
@aki77 
We have considered using both the push and pull_request events simultaneously, but there are several problems with this approach:

Problems:

Duplicate Execution: When a pull request is created, both push and pull_request events are triggered, leading to the execution of two CI workflows. This results in the same code being tested twice.
Resource Wastage: Running two CI workflows for the same code consumes unnecessary resources, including time and compute power.
Increased Costs: The additional CI runs can increase the cost of using CI/CD services, especially if billed by the number of runs or resource usage.
GitHub API Rate Limits: If your workflow makes GitHub API calls and uses a matrix for parallel execution, you may hit the API rate limits more quickly. This can cause some workflow jobs to fail due to the rate limit being exceeded.

**Comment by aki77** [comment]
@hirosi1900day 

I understood.
Is there a problem if I specify both push and pull_request events as follows, and skip the push event and PR if it exists?

```yaml
on:
  push:
  pull_request:
jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      # ...
      - name: Check for Linked PR
        id: check_pr
        run: |
          PR_COUNT=$(gh pr list --head ${{ github.ref_name }} --json number --jq '. | length')
          echo "::set-output name=pr_count::${PR_COUNT}"

      - name: Test
        if: ${{ github.event_name == 'pull_request' || steps.check_pr.pr_count == '0' }}
        run: bundle exec rspec
```

**Comment by hirosi1900day** [comment]
@aki77 
Thank you, that's a great idea!

**Pull request closed without merging**
